# Generated by Django 5.1.3 on 2024-11-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandmodel',
            old_name='name',
            new_name='brand_name',
        ),
    ]
