# Generated by Django 5.1.3 on 2024-11-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_carmodel_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
