# Generated by Django 5.1.3 on 2024-11-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_carmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
