# Generated by Django 5.1.3 on 2024-11-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_carmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='slug',
        ),
    ]
