# Generated by Django 5.1.3 on 2024-11-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_carmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='quantity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
