# Generated by Django 5.1.3 on 2024-11-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_carmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
